[package]
name = "crabby"
authors = ["Ebalo"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
clap = { version = "4.5.4", features = ["derive"] }
reqwest = { version = "0.12.3", features = ["blocking"] }
zip = "0.6.6"
rand = "0.8.5"
serde_json = "1.0.116"
log = { version = "0.4.21" }
fern = { version = "0.6.2", features = ["colored"] }
humantime = "2.1.0"
