services:
  # php 5.x with apache
  template-5.x:
    build:
      context: 5.x
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./5.x:/var/www/html

  # php 7.x with apache
  template-7.x:
    build:
      context: 7.x
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./7.x:/var/www/html

  # php 8.x with apache
  template-8.x:
    build:
      context: 8.x
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./8.x:/var/www/html

  #########################################
  # Sample webshell functionalities       #
  # This sections is for testing purposes #
  #########################################

  # mysql
  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: example
      MARIADB_USER: example_user
      MARIADB_PASSWORD: example_user

  # openldap (default user: admin, password: admin)
  openldap:
    image: osixia/openldap:1.5.0
    ports:
      - '389:389'
      - '636:636'
    environment:
      LDAP_ORGANISATION: "Example Inc."
      LDAP_DOMAIN: "example.org"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_TLS: false
